### ISSUE TITLE
Add gulp task to copy bootstrap fonts

### ISSUE THREAD

**Issue by menor** [resmio/elzar#11]
Or maybe we don't need them, if we override them in the variables (but we still need the icon fonts).

Talk to @fabiennepimenta to see if she wants a custom icon font and create a task that bundles that form svg files

**Comment by fabiennepimenta** [comment]
I think we can stay with the icon font ( It is also best practice) because the page load time.
We could also create our own font , but I think it is not necessary.

**Comment by menor** [comment]
Ok, if we don't need it I just copy the fontawesome font to our assets folder, still I think [svg is better](https://css-tricks.com/icon-fonts-vs-svg/) although icon font is more convenient

**Comment by fabiennepimenta** [comment]
You are right! Let's go to SVG's. The page load with SVG's it's not really a problem. I create a document in illustration and export the icons in SVG. It's better. ;)
