### ISSUE TITLE
Implement master plan for refactoring resmio stylesheets

### ISSUE THREAD

**Issue by menor** [resmio/elzar#15]
The plan is [here](https://github.com/resmio/elzar/wiki/Long-term-plan-for-refactoring-resmio-stylesheets) but we can discuss on this same issue thread.

**Comment by mmarder** [comment]
we want to create smaller issues from this.

**Comment by mmarder** [comment]
with we we mean @menor and @fabiennepimenta

**Comment by menor** [comment]
That plan is actually outdated now, it was about fixing the issues on the current css.

Now we are rebuilding the styles from scratch and then will try to replace all of it, so we need a different plan.

So I'm closing this one
![image](https://cloud.githubusercontent.com/assets/1360794/11524573/08119d66-98cc-11e5-85bb-7955fbc29681.png)
