### ISSUE TITLE
Initial mockup for style guide.

### ISSUE THREAD

**Issue by nsb** [resmio/elzar#2]
![5c63dfee-41e4-11e5-86cf-1c2b69aec9db](https://cloud.githubusercontent.com/assets/16436/9325760/061fa91a-4595-11e5-9d83-f68c288e4af9.png)

**Comment by menor** [comment]
Add some stuff from @PSahner old styleguide:
- Grid system
- Icons
- Images?
- Tables
- Lists

**Comment by menor** [comment]
Since @fabiennepimenta is on board we don't need this anymore
